services:
  invoice-app-backend:
    container_name: invoice-app-backend-container
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: invoice-app-backend:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}