# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: Database123!
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: invoiceapp

# Server config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

# Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: geomehin@gmail.com
EMAIL_PASSWORD: tueusggtvitvcfop
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: mysecret



