jwt:
  secret: secretword

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoiceapp
    username: root
    password: Database123!
  jackson:
    time-zone: America/New_York

  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: geomehin@gmail.com
    password: tueusggtvitvcfop
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

